### ISSUE TITLE
VSCode on Linux gets unresponsive on clicking "Create new project" in Azure Functions extension

### ISSUE THREAD

**Issue by trivikr** [simonaco/serverless-graphql-workshop#2]
Details:
- OS: Ubuntu 18.04.1 LTS
- VSCode September 2018 (version 1.28)

Followed steps in https://github.com/simonaco/serverless-graphql-workshop/blob/master/services/Readme.md#run-locally

VSCode becomes unresponsive at Step 3 - "Create new project", and has to be killed.

Image:
![img_20181107_153307](https://user-images.githubusercontent.com/16024985/48141787-7a0cb580-e2a3-11e8-8b1e-4d6f205ec7bc.jpg)

This appears to be an issue with Azure Functions extensions and not this repo.
Kindly move it to concerned team, so that it doesn't block Linux devs from using Azure Functions in VSCode

**Comment by simonaco** [comment]
thanks a lot @trivikr, I've forwarded this to the team building the extension.
